version: '3'
services:
  movies:
    image: rahamshaik/moviespaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: rahamshaik/trainpaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: rahamshaik/dthpaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: rahamshaik/rechargepaytm:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
